### ISSUE TITLE
Help docs: Investigate hosting for help site

### ISSUE THREAD

**Issue by kevholditch** [ewilde/crane#41]
Look at documentation framework technologies for our help site 
e.g. azure, read the docs

make sure we can point our url at the help site

https://readthedocs.org/

http://cake.readthedocs.org/en/latest/index.html

**Comment by ewilde** [comment]
readthedocs support custom urls using a [cname](http://read-the-docs.readthedocs.org/en/latest/alternate_domains.html)

**Comment by ewilde** [comment]
Okay so, I took a punt at this and I really like the workflow for RTD.

Bascially:

* Create / update a markdown file under /doc
* Check-in
* RTD webhook detects check-in 
 * Builds site and pdf
