### ISSUE TITLE
NuGet package restore doesn't work in VS2012

### ISSUE THREAD

**Issue by fandrei** [ewilde/crane#55]
Steps:
1. Create a new project using crane
2. Try to build it in VS2012

**Comment by ewilde** [comment]
@fandrei we only target VS2013 at the moment (we should make this clear #56). Nuget package restore behaviour has changed between VS2012 and VS2013. @kevholditch @fandrei  should we target VS2012? I've raised this as a separate issue #57

I hope that if you run `.\build.ps1` first and then build it VS2012 it works? (don't have VS2012 to test myself)

**Comment by fandrei** [comment]
@ewilde, yes. It works in VS2012 after build.ps1 execution.
